/************************************************************************************************************************                                                                                         
 
              ***                                                            ***          *****                          
            ****                                                            *****       *****                            
          ****                                                                         *****                             
    ****************         **********         ****       *****        *****       *****             ************      
       ****             *****                *****       *****       *****       ******         *******                
      ***            ****       ****       *****       *****        ****        *****        ******      *****         
    ****           *****       ****       *****       *****       *****       *****        *****        ****           
   ****       ********       ****     *******       *****      ******       ******      *******       *****      ***** 
  *************** ***** *********  **********************************************************************************   
   ********          *****************     *******      ******     ********     *******       *******    *******         
                           ******                                                                                        
                         ******                                                                                          
                        ****                                                                          
                       ***                                                                         SOCIAL | MOBILE | WEB  
  
 
  
Crafted by    : Mayank Sharma
               : msharma@tquila.com 
               : www.tquila.com

 Code purpose  : 


 Birthday      : 03/10/2014
 Api version   : v31

 ****************************************************************************************************************************/

public with sharing class CustomerCommunityController{

    public String AHoverColor {get;set;}
    public String BodyBodyDivBFilterViewFontSize {get;set;}
    public String BodyBodyDivBFilterViewHeight {get;set;}
    public String BodyBPageTitleFontSize {get;set;}
    public String BodyBPageTitleFontWeight {get;set;}
    public String BodyBPageTitleLineHeight {get;set;}
    public String BodyBPageTitlePtBodyPageTypeFontFamily {get;set;}
    public String BodyBPageTitlePtBodyPageTypeFontSize {get;set;}
    public String BodyBPageTitlePtBodyPageTypeFontWeight {get;set;}
    public String BodyButtonBorderColor {get;set;}
    public String BodyButtonBorderRadius {get;set;}
    public String BodyButtonBorderStyle {get;set;}
    public String BodyButtonBorderWidth {get;set;}
    public String BodyButtonHeight {get;set;}
    public String BodyButtonMoxBgImage {get;set;}
    public String BodyButtonMsBgImage {get;set;}
    public String BodyButtonWebBgImage {get;set;}
    public String BodyDivBgColor {get;set;}
    public String BodyDivDisplay {get;set;}
    public String BodyDivFloat {get;set;}
    public String BodyDivMargin {get;set;}
    public String BodyDivMarginTop {get;set;}
    public String BodyTablePaddingBottom {get;set;}
    public String BPageHeaderBgImage {get;set;}
    public String BrandPrimaryBgrBgColor {get;set;}
    public String BrandPrimaryBgrFontFamily {get;set;}
    public String BrandPrimaryBgrFontSize {get;set;}
    public String BrandPrimaryBgrHeight {get;set;}
    public String BrandPrimaryBrdBorderTopColor {get;set;}
    public String BrandPrimaryBrdMarginTop{get;set;}
    public String BrandPrimaryFgrColor {get;set;}
    public String BrandPrimaryFgrFontFamily {get;set;}
    public String BrandPrimaryFgrFontSize {get;set;}
    public String BrandPrimaryFgrFontWeight {get;set;}
    public String BrandQuaternaryBgrMozBg {get;set;}
    public String BrandQuaternaryBgrMsBg {get;set;}
    public String BrandQuaternaryBgrWebBg {get;set;}
    public String BrandSecondaryBrdBorderColor {get;set;}
    public String BRelatedListCaseBlockBTitleMargin {get;set;}
    public String BRelatedListCaseBlockDisplay {get;set;}
    public String BRelatedListCaseBlockPosition {get;set;}
    public String BRelatedListCaseMarginLeft {get;set;}
    public String BRelatedListCaseMarginTop {get;set;}
    public String BRelatedListContactBlockBTitleMargin {get;set;}
    public String BRelatedListContactBlockDisplay {get;set;}
    public String BRelatedListContactBlockMarginLeft {get;set;}
    public String BRelatedListContactBlockMarginTop {get;set;}
    public String BRelatedListContactBlockPosition {get;set;}
    public String BRelatedListCustom20BlockBTitleMargin {get;set;}
    public String BRelatedListCustom20BlockDisplay {get;set;}
    public String BRelatedListCustom20BlockMarginLeft {get;set;}
    public String BRelatedListCustom20BlockMarginTop {get;set;}
    public String BRelatedListCustom20BlockPosition {get;set;}
    public String BRelatedListCustom99BlockBTitleMargin {get;set;}
    public String BRelatedListDisplay {get;set;}
    public String BRelatedListMarginLeft {get;set;}
    public String BRelatedListMarginTop {get;set;}
    public String BRelatedListPosition {get;set;}
    public String CommunitybodyBgColor {get;set;}
    public String CommunitybodyDisplay {get;set;}
    public String CommunitybodyMinHeight {get;set;}
    public String CommunitybodyPosition {get;set;}
    public String CommunitybodyWidth {get;set;}
    public String CommunityFooter {get;set;}
    public String CommunityfooterBgColor {get;set;}
    public String CommunityfooterBgPosition {get;set;}
    public String CommunityfooterBgURL {get;set;}
    public String CommunityfooterFooterBgRepeat {get;set;}
    public String CommunityfooterHeight {get;set;}
    public String CommunityfooterLeft {get;set;}
    public String CommunityfooterMarginLeft {get;set;}
    public String CommunityfooterMarginRight {get;set;}
    public String CommunityfooterWidth {get;set;}
    public String CommunityheaderBgColor {get;set;}
    public String CommunityheaderbotHeight {get;set;}
    public String CommunityheaderbotMarginTop {get;set;}
    public String CommunityheaderbotWidth {get;set;}
    public String CommunityheaderHeight {get;set;}
    public String CommunityheaderMargin {get;set;}
    public String CommunityheadertopHeight {get;set;}
    public String CommunityheadertopWidth {get;set;}
    public String CommunityheaderWidth {get;set;}
    public String CommunityLogo {get;set;}
    public String CommunitylogoBgSize {get;set;}
    public String CommunitylogoBgURL {get;set;}
    public String CommunitylogoFloat {get;set;}
    public String CommunitylogoHeight {get;set;}
    public String CommunitylogoMarginTop {get;set;}
    public String CommunitylogoWidth {get;set;}
    public String CommunityPageTitleIcon {get;set;}
    public String CommunityPrimaryColor {get;set;}
    public String CommunitySearchBox {get;set;}
    public String CommunitysearchFloat {get;set;}
    public String CommunitysearchHeight {get;set;}
    public String CommunitysearchPadding {get;set;}
    public String CommunitysearchSearchButtonDisplay {get;set;}
    public String CommunitysearchSearchFocusOutlineWidth {get;set;}
    public String CommunitysearchSearchTextboxBgColor {get;set;}
    public String CommunitysearchSearchTextboxBorderColor {get;set;}
    public String CommunitysearchSearchTextboxBorderFontSi {get;set;}
    public String CommunitysearchSearchTextboxBorderHeight {get;set;}
    public String CommunitysearchSearchTextboxBorderMargin {get;set;}
    public String CommunitysearchSearchTextboxBorderPLeft {get;set;}
    public String CommunitysearchSearchTextboxBorderPositi {get;set;}
    public String CommunitysearchSearchTextboxBorderRadius {get;set;}
    public String CommunitysearchSearchTextboxBorderStyle {get;set;}
    public String CommunitysearchSearchTextboxBorderWidth {get;set;}
    public String CommunitysearchSearchTextboxColor {get;set;}
    public String CommunitysearchSearchTextboxFontFamily {get;set;}
    public String CommunitysearchSearchTextboxFontSize {get;set;}
    public String CommunitysearchSearchTextboxHeight {get;set;}
    public String CommunitysearchSearchTextboxLineHeight {get;set;}
    public String CommunitysearchSearchTextboxTextAlign {get;set;}
    public String CommunitysearchSearchTextboxTexTShadow {get;set;}
    public String CommunitysearchSearchTextboxWidth {get;set;}
    public String CommunitysearchWidth {get;set;}
    public String CommunitySecondaryColor {get;set;}
    public String CommunityTertiaryColor {get;set;}
    public String CommunityWidth {get;set;}
    public String CommunitywrapperDisplay {get;set;}
    public String CommunitywrapperMargin {get;set;}
    public String CommunitywrapperWidth {get;set;}
    public String ContentWrapperMinWidth {get;set;}
    public String ContentWrapperMozBg {get;set;}
    public String ContentWrapperMsBg {get;set;}
    public String ContentWrapperWebBg {get;set;}
    public String FooterclassMarginLeft {get;set;}
    public String FooterContentColor {get;set;}
    public String FooterContentFontFamily {get;set;}
    public String FooterContentFontSize {get;set;}
    public String FooterContentTextDecoration {get;set;}
    public String HandlebarContainerBg {get;set;}
    public String HandlebarContainerHeight {get;set;}
    public String HandlebarContainerRight {get;set;}
    public String HandlebarContainerWidth {get;set;}
    public String HashZenNavMenusMarginRight {get;set;}
    public String HomeTabBorderTopColor {get;set;}
    public String HtmlBgColor {get;set;}
    public String HtmlBgImage {get;set;} 
    public String HtmlPosition {get;set;}
    public String IdeaContentIdeaBodyWidth {get;set;}
    public String IdeaPageLayoutWithProfileSidebarDisplay {get;set;}
    public String IdeaPageLayoutWithProfileSidebarOverflow {get;set;}
    public String IdeaPageLayoutWithProfileSidebarWidth {get;set;}
    public String PageSectionMarginTop {get;set;}
    public String PageTitleIconDisplay {get;set;}
    public String PageTitleIconFloat {get;set;}
    public String PageTitleIconMarginRight {get;set;}
    public String PageTitleIconWidth {get;set;}
    public String PageWidgetBoxSizing {get;set;}
    public String PageWidgetFloat {get;set;}
    public String PageWidgetNthChildPaddingRight {get;set;}
    public String PageWidgetPFirstLetterFontSize {get;set;}
    public String pageWidgetPLineHeight {get;set;}
    public String pageWidgetPMargin {get;set;}
    public String PageWidgetPPadding {get;set;}
    public String PageWidgetWidth {get;set;}
    public String PartnerAccountId {get;set;}
    public String RelatedListIconDisplay {get;set;}
    public String SearchButtonDivBgPosition {get;set;}
    public String SearchButtonDivBgRepeat {get;set;}
    public String SearchButtonDivBorderColor {get;set;}
    public String SearchButtonDivBorderHeight {get;set;}
    public String SearchButtonDivBorderRadius {get;set;}
    public String SearchButtonDivBorderStyle {get;set;}
    public String SearchButtonDivBorderWidth {get;set;}
    public String SearchButtonDivHoverBgPosition {get;set;}
    public String SearchButtonDivHoverBgRepeat {get;set;}
    public String SearchButtonDivHoverBorderColor {get;set;}
    public String SearchButtonDivHoverBorderRadius {get;set;}
    public String SearchButtonDivHoverBorderStyle {get;set;}
    public String SearchButtonDivHoverBorderWidth {get;set;}
    public String SearchButtonDivHoverHeight {get;set;}
    public String SearchButtonDivHoverMargin {get;set;}
    public String SearchButtonDivHoverMozBgImage {get;set;}
    public String SearchButtonDivHoverMsBgImage {get;set;}
    public String SearchButtonDivHoverWebBgImage {get;set;}
    public String SearchButtonDivHoverWidth {get;set;}
    public String SearchButtonDivMargin {get;set;}
    public String SearchButtonDivMozBgImage {get;set;}
    public String SearchButtonDivMsBgImage {get;set;}
    public String SearchButtonDivWebBgImage {get;set;}
    public String SearchButtonDivWidth {get;set;}
    public String SideBarBg {get;set;}
    public String SideBarBgColor {get;set;}
    public String SideBarBorderTopLeftRadius {get;set;}
    public String SidebarCollapsedBg {get;set;}
    public String SideBarFontFamily {get;set;}
    public String SideBarFontSize {get;set;}
    public String SidebarModuleHeaderBg {get;set;}
    public String SidebarModuleHeaderDisplay {get;set;}
    public String SidebarModuleHeaderPadding {get;set;}
    public String SideBarPaddingLeft {get;set;}
    public String SpeechIconHeight {get;set;}
    public String SpeechIconMarginRight {get;set;}
    public String SpeechIconWidth {get;set;}
    public String TabBarMargin {get;set;}
    public String UserPhotoBorderRadius {get;set;}
    public String UserPhotoFloat {get;set;}
    public String UserPhotoHeight {get;set;}
    public String UserPhotoMarginRight {get;set;}
    public String UserPhotoWidth {get;set;}
    public String WelcomeImageBorderRadius {get;set;}
    public String WelcomeImageWidth {get;set;}
    public String WelcomeMessageBg {get;set;}
    public String WelcomeMessageBorderRadius {get;set;}
    public String WelcomeMessageColor {get;set;}
    public String WelcomeMessageDisplay {get;set;}
    public String WelcomeMessageFontFamily {get;set;}
    public String WelcomeMessageFontSize {get;set;}
    public String WelcomeMessageFontStyle {get;set;}
    public String WelcomeMessageHeight {get;set;}
    public String WelcomeMessageHoverCursor {get;set;}
    public String WelcomeMessageHoverOpacity {get;set;}
    public String WelcomeMessageLineHeight {get;set;}
    public String WelcomeMessageMaxWidth {get;set;}
    public String WelcomeMessageOpacity {get;set;}
    public String WelcomeMessagePadding {get;set;}
    public String WelcomeMessagePDisplay {get;set;}
    public String WelcomeMessagePFloat {get;set;}
    public String WelcomeMessagePMargin {get;set;}
    public String WelcomeMessagePosition {get;set;}
    public String WelcomeMessageTextAlign {get;set;}
    public String WelcomeMessageTop {get;set;}
    public String WidgetContentBg {get;set;}
    public String WidgetContentBorderRadius {get;set;}
    public String WidgetContentMinHeight {get;set;}
    public String WidgetContentPadding {get;set;}
    public String WidgetContentTableWidth {get;set;}
    public String WidgetLabelFontSize {get;set;}
    public String WidgetRowWidth {get;set;}
    public String WidgetTitleBg {get;set;}
    public String WidgetTitleBorderRadius {get;set;}
    public String WidgetTitleColor {get;set;}
    public String WidgetTitleColorTextTransform {get;set;}
    public String WidgetTitleFloat {get;set;}
    public String WidgetTitleFontSize {get;set;}
    public String WidgetTitleHeight {get;set;}
    public String WidgetTitleImgHeight {get;set;}
    public String WidgetTitleImgMarginTop {get;set;}
    public String WidgetTitleImgWidth {get;set;}
    public String WidgetTitleLineHeight {get;set;}
    public String WidgetTitleMarginBottom {get;set;}
    public String WidgetTitleMargingTop {get;set;}
    public String WidgetTitlePadding {get;set;}
    public String ZenActiveBg {get;set;}
    public String ZenActiveBorderColor {get;set;}
    public String ZenActiveBorderStyle {get;set;}
    public String ZenActiveBorderTopLeftRadius {get;set;}
    public String ZenActiveBorderTopRightRadius {get;set;}
    public String ZenActiveBorderWidth {get;set;}
    public String ZenActiveBoxShadow {get;set;}
    public String ZenActiveColor {get;set;}
    public String ZenActiveMarginRight {get;set;}
    public String ZenBodyZenBrdPaletteBorderRadius {get;set;}
    public String ZenBodyZenBrdPaletteBoxShadow {get;set;}
    public String ZenHighlightBtnBorder {get;set;}
    public String ZenHighlightBtnBorderColor {get;set;}
    public String ZenHighlightBtnBorderRadius {get;set;}
    public String ZenHighlightBtnBorderStyle {get;set;}
    public String ZenHighlightBtnBorderWidth {get;set;}
    public String ZenHighlightBtnColor {get;set;}
    public String ZenHighlightBtnFontSize {get;set;}
    public String ZenHighlightBtnFontWeight {get;set;}
    public String ZenHighlightBtnHeight {get;set;}
    public String ZenHighlightBtnMargin {get;set;}
    public String ZenHighlightBtnMozBgImage {get;set;}
    public String ZenHighlightBtnMsBgImage {get;set;}
    public String ZenHighlightBtnWebBgImage {get;set;}
    public String ZenNavMenusMarginRight {get;set;}
    public String ZenTabContainerBg {get;set;}
    public String ZenTabContainerBoxShadow {get;set;}
    public String ZenTabContainerHeight {get;set;}
    public String ZenTabContainerPosition {get;set;}
    public String ZenTabContainerTop {get;set;}
    public String ZenTabMenuAColor {get;set;}
    public String ZenTabMenuADisplay {get;set;}
    public String ZenTabMenuAFontFamily {get;set;}
    public String ZenTabMenuAFontSize {get;set;}
    public String ZenTabMenuAFontWeight {get;set;}
    public String ZenTabMenuAHoverColor {get;set;}
    public String ZenTabMenuAHoverTextDecoration {get;set;}
    public String ZenTabMenuAPadding {get;set;}
    public String ZenTabMenuATextAlign {get;set;}
    public String ZenTabMenuATextTransform {get;set;}
    public String ZenTabMenuBg {get;set;}
    public String ZenTabMenuBorder {get;set;}
    public String ZenTabMenuBorderRadius {get;set;}
    public String ZenTabMenuHeight {get;set;}
    public String ZenTabMenuLineHeight {get;set;}
    public String ZenTabMenuMargin {get;set;}
    public String ZenTabMenuMinWidth {get;set;}
    public String ZenTabMenuPadding {get;set;}
    public String ZenTabMenuTextAlign {get;set;}
    public String ZenZenTabMenuPadding {get;set;}
    public String ZenActiveAHoverColor {get;set;}
    public String ZenActiveAHoverBorderWidth {get;set;}
    public String ZenActiveAHoverBorderStyle {get;set;}
    public String ZenActiveAHoverBorderColor {get;set;} 
    public String BodyTableMarginBottom {get;set;}
    public String brandSecondaryBrdWidth {get;set;}
    public String brandSecondaryBrdMarginLeft {get;set;}
    public String sideBarMarginTop {get;set;}

    /** 
        This loads initializes styling parameters for the Customer portal once counterparty logs in
    */
    public void initializeBrandingParameters(){
        
        User loggedInUser = [select Id, contact.Account.ParentId, contact.AccountId from User where Id =:  Userinfo.getUserId()];
        List<DDCustomerBrandingParameters__c> customerBrandingParamentersList = DDCustomerBrandingParameters__c.getall().values();
        for(DDCustomerBrandingParameters__c customerBrandingParamentersVal : customerBrandingParamentersList){
            if(String.valueOf(loggedInUser.contact.Account.ParentId).substring(0,15).equals(customerBrandingParamentersVal.PartnerAccountId__c)){
                AHoverColor = customerBrandingParamentersVal.AHoverColor__c;
                BodyBodyDivBFilterViewFontSize = customerBrandingParamentersVal.BodyBodyDivBFilterViewFontSize__c;
                BodyBodyDivBFilterViewHeight = customerBrandingParamentersVal.BodyBodyDivBFilterViewHeight__c;
                BodyBPageTitleFontSize = customerBrandingParamentersVal.BodyBPageTitleFontSize__c;
                BodyBPageTitleFontWeight = customerBrandingParamentersVal.BodyBPageTitleFontWeight__c;
                BodyBPageTitleLineHeight = customerBrandingParamentersVal.BodyBPageTitleLineHeight__c;
                BodyBPageTitlePtBodyPageTypeFontFamily = customerBrandingParamentersVal.BodyBPageTitlePtBodyPageTypeFontFamily__c;
                BodyBPageTitlePtBodyPageTypeFontSize = customerBrandingParamentersVal.BodyBPageTitlePtBodyPageTypeFontSize__c;
                BodyBPageTitlePtBodyPageTypeFontWeight = customerBrandingParamentersVal.BodyBPageTitlePtBodyPageTypeFontWeight__c;
                BodyButtonBorderColor = customerBrandingParamentersVal.BodyButtonBorderColor__c;
                BodyButtonBorderRadius = customerBrandingParamentersVal.BodyButtonBorderRadius__c;
                BodyButtonBorderStyle = customerBrandingParamentersVal.BodyButtonBorderStyle__c;
                BodyButtonBorderWidth = customerBrandingParamentersVal.BodyButtonBorderWidth__c;
                BodyButtonHeight = customerBrandingParamentersVal.BodyButtonHeight__c;
                BodyButtonMoxBgImage = customerBrandingParamentersVal.BodyButtonMoxBgImage__c;
                BodyButtonMsBgImage = customerBrandingParamentersVal.BodyButtonMsBgImage__c;
                BodyButtonWebBgImage = customerBrandingParamentersVal.BodyButtonWebBgImage__c;
                BodyDivBgColor = customerBrandingParamentersVal.BodyDivBgColor__c;
                BodyDivDisplay = customerBrandingParamentersVal.BodyDivDisplay__c;
                BodyDivFloat = customerBrandingParamentersVal.BodyDivFloat__c;
                BodyDivMargin = customerBrandingParamentersVal.BodyDivMargin__c;
                BodyDivMarginTop = customerBrandingParamentersVal.BodyDivMarginTop__c;
                BodyTablePaddingBottom = customerBrandingParamentersVal.BodyTablePaddingBottom__c;
                BPageHeaderBgImage = customerBrandingParamentersVal.BPageHeaderBgImage__c;
                BrandPrimaryBgrBgColor = customerBrandingParamentersVal.BrandPrimaryBgrBgColor__c;
                BrandPrimaryBgrFontFamily = customerBrandingParamentersVal.BrandPrimaryBgrFontFamily__c;
                BrandPrimaryBgrFontSize = customerBrandingParamentersVal.BrandPrimaryBgrFontSize__c;
                BrandPrimaryBgrHeight = customerBrandingParamentersVal.BrandPrimaryBgrHeight__c;
                BrandPrimaryBrdBorderTopColor = customerBrandingParamentersVal.BrandPrimaryBrdBorderTopColor__c;
                BrandPrimaryBrdMarginTop = customerBrandingParamentersVal.BrandPrimaryBrdMarginTop__c;
                BrandPrimaryFgrColor = customerBrandingParamentersVal.BrandPrimaryFgrColor__c;
                BrandPrimaryFgrFontFamily = customerBrandingParamentersVal.BrandPrimaryFgrFontFamily__c;
                BrandPrimaryFgrFontSize = customerBrandingParamentersVal.BrandPrimaryFgrFontSize__c;
                BrandPrimaryFgrFontWeight = customerBrandingParamentersVal.BrandPrimaryFgrFontWeight__c;
                BrandQuaternaryBgrMozBg = customerBrandingParamentersVal.BrandQuaternaryBgrMozBg__c;
                BrandQuaternaryBgrMsBg = customerBrandingParamentersVal.BrandQuaternaryBgrMsBg__c;
                BrandQuaternaryBgrWebBg = customerBrandingParamentersVal.BrandQuaternaryBgrWebBg__c;
                BrandSecondaryBrdBorderColor = customerBrandingParamentersVal.BrandSecondaryBrdBorderColor__c;
                BRelatedListCaseBlockBTitleMargin = customerBrandingParamentersVal.BRelatedListCaseBlockBTitleMargin__c;
                BRelatedListCaseBlockDisplay = customerBrandingParamentersVal.BRelatedListCaseBlockDisplay__c;
                BRelatedListCaseBlockPosition = customerBrandingParamentersVal.BRelatedListCaseBlockPosition__c;
                BRelatedListCaseMarginLeft = customerBrandingParamentersVal.BRelatedListCaseMarginLeft__c;
                BRelatedListCaseMarginTop = customerBrandingParamentersVal.BRelatedListCaseMarginTop__c;
                BRelatedListContactBlockBTitleMargin = customerBrandingParamentersVal.BRelatedListContactBlockBTitleMargin__c;
                BRelatedListContactBlockDisplay = customerBrandingParamentersVal.BRelatedListContactBlockDisplay__c;
                BRelatedListContactBlockMarginLeft = customerBrandingParamentersVal.BRelatedListContactBlockMarginLeft__c;
                BRelatedListContactBlockMarginTop = customerBrandingParamentersVal.BRelatedListContactBlockMarginTop__c;
                BRelatedListContactBlockPosition = customerBrandingParamentersVal.BRelatedListContactBlockPosition__c;
                BRelatedListCustom20BlockBTitleMargin = customerBrandingParamentersVal.BRelatedListCustom20BlockBTitleMargin__c;
                BRelatedListCustom20BlockDisplay = customerBrandingParamentersVal.BRelatedListCustom20BlockDisplay__c;
                BRelatedListCustom20BlockMarginLeft = customerBrandingParamentersVal.BRelatedListCustom20BlockMarginLeft__c;
                BRelatedListCustom20BlockMarginTop = customerBrandingParamentersVal.BRelatedListCustom20BlockMarginTop__c;
                BRelatedListCustom20BlockPosition = customerBrandingParamentersVal.BRelatedListCustom20BlockPosition__c;
                BRelatedListCustom99BlockBTitleMargin = customerBrandingParamentersVal.BRelatedListCustom99BlockBTitleMargin__c;
                BRelatedListDisplay = customerBrandingParamentersVal.BRelatedListDisplay__c;
                BRelatedListMarginLeft = customerBrandingParamentersVal.BRelatedListMarginLeft__c;
                BRelatedListMarginTop = customerBrandingParamentersVal.BRelatedListMarginTop__c;
                BRelatedListPosition = customerBrandingParamentersVal.BRelatedListPosition__c;
                CommunitybodyBgColor = customerBrandingParamentersVal.CommunitybodyBgColor__c;
                CommunitybodyDisplay = customerBrandingParamentersVal.CommunitybodyDisplay__c;
                CommunitybodyMinHeight = customerBrandingParamentersVal.CommunitybodyMinHeight__c;
                CommunitybodyPosition = customerBrandingParamentersVal.CommunitybodyPosition__c;
                CommunitybodyWidth = customerBrandingParamentersVal.CommunitybodyWidth__c;
                CommunityFooter = customerBrandingParamentersVal.Community_Footer__c;
                CommunityfooterBgColor = customerBrandingParamentersVal.CommunityfooterBgColor__c;
                CommunityfooterBgPosition = customerBrandingParamentersVal.CommunityfooterBgPosition__c;
                CommunityfooterBgURL = customerBrandingParamentersVal.CommunityfooterBgURL__c;
                CommunityfooterFooterBgRepeat = customerBrandingParamentersVal.CommunityfooterFooterBgRepeat__c;
                CommunityfooterHeight = customerBrandingParamentersVal.CommunityfooterHeight__c;
                CommunityfooterLeft = customerBrandingParamentersVal.CommunityfooterLeft__c;
                CommunityfooterMarginLeft = customerBrandingParamentersVal.CommunityfooterMarginLeft__c;
                CommunityfooterMarginRight = customerBrandingParamentersVal.CommunityfooterMarginRight__c;
                CommunityfooterWidth = customerBrandingParamentersVal.CommunityfooterWidth__c;
                CommunityheaderBgColor = customerBrandingParamentersVal.CommunityheaderBgColor__c;
                CommunityheaderbotHeight = customerBrandingParamentersVal.CommunityheaderbotHeight__c;
                CommunityheaderbotMarginTop = customerBrandingParamentersVal.CommunityheaderbotMarginTop__c;
                CommunityheaderbotWidth = customerBrandingParamentersVal.CommunityheaderbotWidth__c;
                CommunityheaderHeight = customerBrandingParamentersVal.CommunityheaderHeight__c;
                CommunityheaderMargin = customerBrandingParamentersVal.CommunityheaderMargin__c;
                CommunityheadertopHeight = customerBrandingParamentersVal.CommunityheadertopHeight__c;
                CommunityheadertopWidth = customerBrandingParamentersVal.CommunityheadertopWidth__c;
                CommunityheaderWidth = customerBrandingParamentersVal.CommunityheaderWidth__c;
                CommunityLogo = customerBrandingParamentersVal.CommunityLogo__c;
                CommunitylogoBgSize = customerBrandingParamentersVal.CommunitylogoBgSize__c;
                CommunitylogoBgURL = customerBrandingParamentersVal.CommunitylogoBgURL__c;
                CommunitylogoFloat = customerBrandingParamentersVal.CommunitylogoFloat__c;
                CommunitylogoHeight = customerBrandingParamentersVal.CommunitylogoHeight__c;
                CommunitylogoMarginTop = customerBrandingParamentersVal.CommunitylogoMarginTop__c;
                CommunitylogoWidth = customerBrandingParamentersVal.CommunitylogoWidth__c;
                CommunityPageTitleIcon = customerBrandingParamentersVal.CommunityPageTitleIcon__c;
                CommunityPrimaryColor = customerBrandingParamentersVal.Community_Primary_Color__c;
                CommunitySearchBox = customerBrandingParamentersVal.Community_Search_Box__c;
                CommunitysearchFloat = customerBrandingParamentersVal.CommunitysearchFloat__c;
                CommunitysearchHeight = customerBrandingParamentersVal.CommunitysearchHeight__c;
                CommunitysearchPadding = customerBrandingParamentersVal.CommunitysearchPadding__c;
                CommunitysearchSearchButtonDisplay = customerBrandingParamentersVal.CommunitysearchSearchButtonDisplay__c;
                CommunitysearchSearchFocusOutlineWidth = customerBrandingParamentersVal.CommunitysearchSearchFocusOutlineWidth__c;
                CommunitysearchSearchTextboxBgColor = customerBrandingParamentersVal.CommunitysearchSearchTextboxBgColor__c;
                CommunitysearchSearchTextboxBorderColor = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderColor__c;
                CommunitysearchSearchTextboxBorderFontSi = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderFontSi__c;
                CommunitysearchSearchTextboxBorderHeight = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderHeight__c;
                CommunitysearchSearchTextboxBorderMargin = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderMargin__c;
                CommunitysearchSearchTextboxBorderPLeft = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderPLeft__c;
                CommunitysearchSearchTextboxBorderPositi = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderPositi__c;
                CommunitysearchSearchTextboxBorderRadius = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderRadius__c;
                CommunitysearchSearchTextboxBorderStyle = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderStyle__c;
                CommunitysearchSearchTextboxBorderWidth = customerBrandingParamentersVal.CommunitysearchSearchTextboxBorderWidth__c;
                CommunitysearchSearchTextboxColor = customerBrandingParamentersVal.CommunitysearchSearchTextboxColor__c;
                CommunitysearchSearchTextboxFontFamily = customerBrandingParamentersVal.CommunitysearchSearchTextboxFontFamily__c;
                CommunitysearchSearchTextboxFontSize = customerBrandingParamentersVal.CommunitysearchSearchTextboxFontSize__c;
                CommunitysearchSearchTextboxHeight = customerBrandingParamentersVal.CommunitysearchSearchTextboxHeight__c;
                CommunitysearchSearchTextboxLineHeight = customerBrandingParamentersVal.CommunitysearchSearchTextboxLineHeight__c;
                CommunitysearchSearchTextboxTextAlign = customerBrandingParamentersVal.CommunitysearchSearchTextboxTextAlign__c;
                CommunitysearchSearchTextboxTexTShadow = customerBrandingParamentersVal.CommunitysearchSearchTextboxTexTShadow__c;
                CommunitysearchSearchTextboxWidth = customerBrandingParamentersVal.CommunitysearchSearchTextboxWidth__c;
                CommunitysearchWidth = customerBrandingParamentersVal.CommunitysearchWidth__c;
                CommunitySecondaryColor = customerBrandingParamentersVal.Community_Secondary_Color__c;
                CommunityTertiaryColor = customerBrandingParamentersVal.Community_Tertiary_Color__c;
                CommunityWidth = customerBrandingParamentersVal.Community_Width__c;
                CommunitywrapperDisplay = customerBrandingParamentersVal.CommunitywrapperDisplay__c;
                CommunitywrapperMargin = customerBrandingParamentersVal.CommunitywrapperMargin__c;
                CommunitywrapperWidth = customerBrandingParamentersVal.CommunitywrapperWidth__c;
                ContentWrapperMinWidth = customerBrandingParamentersVal.ContentWrapperMinWidth__c;
                ContentWrapperMozBg = customerBrandingParamentersVal.ContentWrapperMozBg__c;
                ContentWrapperMsBg = customerBrandingParamentersVal.ContentWrapperMsBg__c;
                ContentWrapperWebBg = customerBrandingParamentersVal.ContentWrapperWebBg__c;
                FooterclassMarginLeft = customerBrandingParamentersVal.FooterclassMarginLeft__c;
                FooterContentColor = customerBrandingParamentersVal.FooterContentColor__c;
                FooterContentFontFamily = customerBrandingParamentersVal.FooterContentFontFamily__c;
                FooterContentFontSize = customerBrandingParamentersVal.FooterContentFontSize__c;
                FooterContentTextDecoration = customerBrandingParamentersVal.FooterContentTextDecoration__c;
                HandlebarContainerBg = customerBrandingParamentersVal.HandlebarContainerBg__c;
                HandlebarContainerHeight = customerBrandingParamentersVal.HandlebarContainerHeight__c;
                HandlebarContainerRight = customerBrandingParamentersVal.HandlebarContainerRight__c;
                HandlebarContainerWidth = customerBrandingParamentersVal.HandlebarContainerWidth__c;
                HashZenNavMenusMarginRight = customerBrandingParamentersVal.HashZenNavMenusMarginRight__c;
                HomeTabBorderTopColor = customerBrandingParamentersVal.HomeTabBorderTopColor__c;
                HtmlBgColor = customerBrandingParamentersVal.HtmlBgColor__c;
                HtmlBgImage = customerBrandingParamentersVal.HtmlBgImage__c;
                HtmlPosition = customerBrandingParamentersVal.HtmlPosition__c;
                IdeaContentIdeaBodyWidth = customerBrandingParamentersVal.IdeaContentIdeaBodyWidth__c;
                IdeaPageLayoutWithProfileSidebarDisplay = customerBrandingParamentersVal.IdeaPageLayoutWithProfileSidebarDisplay__c;
                IdeaPageLayoutWithProfileSidebarOverflow = customerBrandingParamentersVal.IdeaPageLayoutWithProfileSidebarOverflow__c;
                IdeaPageLayoutWithProfileSidebarWidth = customerBrandingParamentersVal.IdeaPageLayoutWithProfileSidebarWidth__c;
                PageSectionMarginTop = customerBrandingParamentersVal.PageSectionMarginTop__c;
                PageTitleIconDisplay = customerBrandingParamentersVal.PageTitleIconDisplay__c;
                PageTitleIconFloat = customerBrandingParamentersVal.PageTitleIconFloat__c;
                PageTitleIconMarginRight = customerBrandingParamentersVal.PageTitleIconMarginRight__c;
                PageTitleIconWidth = customerBrandingParamentersVal.PageTitleIconWidth__c;
                PageWidgetBoxSizing = customerBrandingParamentersVal.PageWidgetBoxSizing__c;
                PageWidgetFloat = customerBrandingParamentersVal.PageWidgetFloat__c;
                PageWidgetNthChildPaddingRight = customerBrandingParamentersVal.PageWidgetNthChildPaddingRight__c;
                PageWidgetPFirstLetterFontSize = customerBrandingParamentersVal.PageWidgetPFirstLetterFontSize__c;
                pageWidgetPLineHeight = customerBrandingParamentersVal.pageWidgetPLineHeight__c;
                pageWidgetPMargin = customerBrandingParamentersVal.pageWidgetPMargin__c;
                PageWidgetPPadding = customerBrandingParamentersVal.PageWidgetPPadding__c;
                PageWidgetWidth = customerBrandingParamentersVal.PageWidgetWidth__c;
                PartnerAccountId = customerBrandingParamentersVal.PartnerAccountId__c;
                RelatedListIconDisplay = customerBrandingParamentersVal.RelatedListIconDisplay__c;
                SearchButtonDivBgPosition = customerBrandingParamentersVal.SearchButtonDivBgPosition__c;
                SearchButtonDivBgRepeat = customerBrandingParamentersVal.SearchButtonDivBgRepeat__c;
                SearchButtonDivBorderColor = customerBrandingParamentersVal.SearchButtonDivBorderColor__c;
                SearchButtonDivBorderHeight = customerBrandingParamentersVal.SearchButtonDivBorderHeight__c;
                SearchButtonDivBorderRadius = customerBrandingParamentersVal.SearchButtonDivBorderRadius__c;
                SearchButtonDivBorderStyle = customerBrandingParamentersVal.SearchButtonDivBorderStyle__c;
                SearchButtonDivBorderWidth = customerBrandingParamentersVal.SearchButtonDivBorderWidth__c;
                SearchButtonDivHoverBgPosition = customerBrandingParamentersVal.SearchButtonDivHoverBgPosition__c;
                SearchButtonDivHoverBgRepeat = customerBrandingParamentersVal.SearchButtonDivHoverBgRepeat__c;
                SearchButtonDivHoverBorderColor = customerBrandingParamentersVal.SearchButtonDivHoverBorderColor__c;
                SearchButtonDivHoverBorderRadius = customerBrandingParamentersVal.SearchButtonDivHoverBorderRadius__c;
                SearchButtonDivHoverBorderStyle = customerBrandingParamentersVal.SearchButtonDivHoverBorderStyle__c;
                SearchButtonDivHoverBorderWidth = customerBrandingParamentersVal.SearchButtonDivHoverBorderWidth__c;
                SearchButtonDivHoverHeight = customerBrandingParamentersVal.SearchButtonDivHoverHeight__c;
                SearchButtonDivHoverMargin = customerBrandingParamentersVal.SearchButtonDivHoverMargin__c;
                SearchButtonDivHoverMozBgImage = customerBrandingParamentersVal.SearchButtonDivHoverMozBgImage__c;
                SearchButtonDivHoverMsBgImage = customerBrandingParamentersVal.SearchButtonDivHoverMsBgImage__c;
                SearchButtonDivHoverWebBgImage = customerBrandingParamentersVal.SearchButtonDivHoverWebBgImage__c;
                SearchButtonDivHoverWidth = customerBrandingParamentersVal.SearchButtonDivHoverWidth__c;
                SearchButtonDivMargin = customerBrandingParamentersVal.SearchButtonDivMargin__c;
                SearchButtonDivMozBgImage = customerBrandingParamentersVal.SearchButtonDivMozBgImage__c;
                SearchButtonDivMsBgImage = customerBrandingParamentersVal.SearchButtonDivMsBgImage__c;
                SearchButtonDivWebBgImage = customerBrandingParamentersVal.SearchButtonDivWebBgImage__c;
                SearchButtonDivWidth = customerBrandingParamentersVal.SearchButtonDivWidth__c;
                SideBarBg = customerBrandingParamentersVal.SideBarBg__c;
                SideBarBgColor = customerBrandingParamentersVal.SideBarBgColor__c;
                SideBarBorderTopLeftRadius = customerBrandingParamentersVal.SideBarBorderTopLeftRadius__c;
                SidebarCollapsedBg = customerBrandingParamentersVal.SidebarCollapsedBg__c;
                SideBarFontFamily = customerBrandingParamentersVal.SideBarFontFamily__c;
                SideBarFontSize = customerBrandingParamentersVal.SideBarFontSize__c;
                SidebarModuleHeaderBg = customerBrandingParamentersVal.SidebarModuleHeaderBg__c;
                SidebarModuleHeaderDisplay = customerBrandingParamentersVal.SidebarModuleHeaderDisplay__c;
                SidebarModuleHeaderPadding = customerBrandingParamentersVal.SidebarModuleHeaderPadding__c;
                SideBarPaddingLeft = customerBrandingParamentersVal.SideBarPaddingLeft__c;
                SpeechIconHeight = customerBrandingParamentersVal.SpeechIconHeight__c;
                SpeechIconMarginRight = customerBrandingParamentersVal.SpeechIconMarginRight__c;
                SpeechIconWidth = customerBrandingParamentersVal.SpeechIconWidth__c;
                TabBarMargin = customerBrandingParamentersVal.TabBarMargin__c;
                UserPhotoBorderRadius = customerBrandingParamentersVal.UserPhotoBorderRadius__c;
                UserPhotoFloat = customerBrandingParamentersVal.UserPhotoFloat__c;
                UserPhotoHeight = customerBrandingParamentersVal.UserPhotoHeight__c;
                UserPhotoMarginRight = customerBrandingParamentersVal.UserPhotoMarginRight__c;
                UserPhotoWidth = customerBrandingParamentersVal.UserPhotoWidth__c;
                WelcomeImageBorderRadius = customerBrandingParamentersVal.WelcomeImageBorderRadius__c;
                WelcomeImageWidth = customerBrandingParamentersVal.WelcomeImageWidth__c;
                WelcomeMessageBg = customerBrandingParamentersVal.WelcomeMessageBg__c;
                WelcomeMessageBorderRadius = customerBrandingParamentersVal.WelcomeMessageBorderRadius__c;
                WelcomeMessageColor = customerBrandingParamentersVal.WelcomeMessageColor__c;
                WelcomeMessageDisplay = customerBrandingParamentersVal.WelcomeMessageDisplay__c;
                WelcomeMessageFontFamily = customerBrandingParamentersVal.WelcomeMessageFontFamily__c;
                WelcomeMessageFontSize = customerBrandingParamentersVal.WelcomeMessageFontSize__c;
                WelcomeMessageFontStyle = customerBrandingParamentersVal.WelcomeMessageFontStyle__c;
                WelcomeMessageHeight = customerBrandingParamentersVal.WelcomeMessageHeight__c;
                WelcomeMessageHoverCursor = customerBrandingParamentersVal.WelcomeMessageHoverCursor__c;
                WelcomeMessageHoverOpacity = customerBrandingParamentersVal.WelcomeMessageHoverOpacity__c;
                WelcomeMessageLineHeight = customerBrandingParamentersVal.WelcomeMessageLineHeight__c;
                WelcomeMessageMaxWidth = customerBrandingParamentersVal.WelcomeMessageMaxWidth__c;
                WelcomeMessageOpacity = customerBrandingParamentersVal.WelcomeMessageOpacity__c;
                WelcomeMessagePadding = customerBrandingParamentersVal.WelcomeMessagePadding__c;
                WelcomeMessagePDisplay = customerBrandingParamentersVal.WelcomeMessagePDisplay__c;
                WelcomeMessagePFloat = customerBrandingParamentersVal.WelcomeMessagePFloat__c;
                WelcomeMessagePMargin = customerBrandingParamentersVal.WelcomeMessagePMargin__c;
                WelcomeMessagePosition = customerBrandingParamentersVal.WelcomeMessagePosition__c;
                WelcomeMessageTextAlign = customerBrandingParamentersVal.WelcomeMessageTextAlign__c;
                WelcomeMessageTop = customerBrandingParamentersVal.WelcomeMessageTop__c;
                WidgetContentBg = customerBrandingParamentersVal.WidgetContentBg__c;
                WidgetContentBorderRadius = customerBrandingParamentersVal.WidgetContentBorderRadius__c;
                WidgetContentMinHeight = customerBrandingParamentersVal.WidgetContentMinHeight__c;
                WidgetContentPadding = customerBrandingParamentersVal.WidgetContentPadding__c;
                WidgetContentTableWidth = customerBrandingParamentersVal.WidgetContentTableWidth__c;
                WidgetLabelFontSize = customerBrandingParamentersVal.WidgetLabelFontSize__c;
                WidgetRowWidth = customerBrandingParamentersVal.WidgetRowWidth__c;
                WidgetTitleBg = customerBrandingParamentersVal.WidgetTitleBg__c;
                WidgetTitleBorderRadius = customerBrandingParamentersVal.WidgetTitleBorderRadius__c;
                WidgetTitleColor = customerBrandingParamentersVal.WidgetTitleColor__c;
                WidgetTitleColorTextTransform = customerBrandingParamentersVal.WidgetTitleColorTextTransform__c;
                WidgetTitleFloat = customerBrandingParamentersVal.WidgetTitleFloat__c;
                WidgetTitleFontSize = customerBrandingParamentersVal.WidgetTitleFontSize__c;
                WidgetTitleHeight = customerBrandingParamentersVal.WidgetTitleHeight__c;
                WidgetTitleImgHeight = customerBrandingParamentersVal.WidgetTitleImgHeight__c;
                WidgetTitleImgMarginTop = customerBrandingParamentersVal.WidgetTitleImgMarginTop__c;
                WidgetTitleImgWidth = customerBrandingParamentersVal.WidgetTitleImgWidth__c;
                WidgetTitleLineHeight = customerBrandingParamentersVal.WidgetTitleLineHeight__c;
                WidgetTitleMarginBottom = customerBrandingParamentersVal.WidgetTitleMarginBottom__c;
                WidgetTitleMargingTop = customerBrandingParamentersVal.WidgetTitleMargingTop__c;
                WidgetTitlePadding = customerBrandingParamentersVal.WidgetTitlePadding__c;
                ZenActiveBg = customerBrandingParamentersVal.ZenActiveBg__c;
                ZenActiveBorderColor = customerBrandingParamentersVal.ZenActiveBorderColor__c;
                ZenActiveBorderStyle = customerBrandingParamentersVal.ZenActiveBorderStyle__c;
                ZenActiveBorderTopLeftRadius = customerBrandingParamentersVal.ZenActiveBorderTopLeftRadius__c;
                ZenActiveBorderTopRightRadius = customerBrandingParamentersVal.ZenActiveBorderTopRightRadius__c;
                ZenActiveBorderWidth = customerBrandingParamentersVal.ZenActiveBorderWidth__c;
                ZenActiveBoxShadow = customerBrandingParamentersVal.ZenActiveBoxShadow__c;
                ZenActiveColor = customerBrandingParamentersVal.ZenActiveColor__c;
                ZenActiveMarginRight = customerBrandingParamentersVal.ZenActiveMarginRight__c;
                ZenBodyZenBrdPaletteBorderRadius = customerBrandingParamentersVal.ZenBodyZenBrdPaletteBorderRadius__c;
                ZenBodyZenBrdPaletteBoxShadow = customerBrandingParamentersVal.ZenBodyZenBrdPaletteBoxShadow__c;
                ZenHighlightBtnBorder = customerBrandingParamentersVal.ZenHighlightBtnBorder__c;
                ZenHighlightBtnBorderColor = customerBrandingParamentersVal.ZenHighlightBtnBorderColor__c;
                ZenHighlightBtnBorderRadius = customerBrandingParamentersVal.ZenHighlightBtnBorderRadius__c;
                ZenHighlightBtnBorderStyle = customerBrandingParamentersVal.ZenHighlightBtnBorderStyle__c;
                ZenHighlightBtnBorderWidth = customerBrandingParamentersVal.ZenHighlightBtnBorderWidth__c;
                ZenHighlightBtnColor = customerBrandingParamentersVal.ZenHighlightBtnColor__c;
                ZenHighlightBtnFontSize = customerBrandingParamentersVal.ZenHighlightBtnFontSize__c;
                ZenHighlightBtnFontWeight = customerBrandingParamentersVal.ZenHighlightBtnFontWeight__c;
                ZenHighlightBtnHeight = customerBrandingParamentersVal.ZenHighlightBtnHeight__c;
                ZenHighlightBtnMargin = customerBrandingParamentersVal.ZenHighlightBtnMargin__c;
                ZenHighlightBtnMozBgImage = customerBrandingParamentersVal.ZenHighlightBtnMozBgImage__c;
                ZenHighlightBtnMsBgImage = customerBrandingParamentersVal.ZenHighlightBtnMsBgImage__c;
                ZenHighlightBtnWebBgImage = customerBrandingParamentersVal.ZenHighlightBtnWebBgImage__c;
                ZenNavMenusMarginRight = customerBrandingParamentersVal.ZenNavMenusMarginRight__c;
                ZenTabContainerBg = customerBrandingParamentersVal.ZenTabContainerBg__c;
                ZenTabContainerBoxShadow = customerBrandingParamentersVal.ZenTabContainerBoxShadow__c;
                ZenTabContainerHeight = customerBrandingParamentersVal.ZenTabContainerHeight__c;
                ZenTabContainerPosition = customerBrandingParamentersVal.ZenTabContainerPosition__c;
                ZenTabContainerTop = customerBrandingParamentersVal.ZenTabContainerTop__c;
                ZenTabMenuAColor = customerBrandingParamentersVal.ZenTabMenuAColor__c;
                ZenTabMenuADisplay = customerBrandingParamentersVal.ZenTabMenuADisplay__c;
                ZenTabMenuAFontFamily = customerBrandingParamentersVal.ZenTabMenuAFontFamily__c;
                ZenTabMenuAFontSize = customerBrandingParamentersVal.ZenTabMenuAFontSize__c;
                ZenTabMenuAFontWeight = customerBrandingParamentersVal.ZenTabMenuAFontWeight__c;
                ZenTabMenuAHoverColor = customerBrandingParamentersVal.ZenTabMenuAHoverColor__c;
                ZenTabMenuAHoverTextDecoration = customerBrandingParamentersVal.ZenTabMenuAHoverTextDecoration__c;
                ZenTabMenuAPadding = customerBrandingParamentersVal.ZenTabMenuAPadding__c;
                ZenTabMenuATextAlign = customerBrandingParamentersVal.ZenTabMenuATextAlign__c;
                ZenTabMenuATextTransform = customerBrandingParamentersVal.ZenTabMenuATextTransform__c;
                ZenTabMenuBg = customerBrandingParamentersVal.ZenTabMenuBg__c;
                ZenTabMenuBorder = customerBrandingParamentersVal.ZenTabMenuBorder__c;
                ZenTabMenuBorderRadius = customerBrandingParamentersVal.ZenTabMenuBorderRadius__c;
                ZenTabMenuHeight = customerBrandingParamentersVal.ZenTabMenuHeight__c;
                ZenTabMenuLineHeight = customerBrandingParamentersVal.ZenTabMenuLineHeight__c;
                ZenTabMenuMargin = customerBrandingParamentersVal.ZenTabMenuMargin__c;
                ZenTabMenuMinWidth = customerBrandingParamentersVal.ZenTabMenuMinWidth__c;
                ZenTabMenuPadding = customerBrandingParamentersVal.ZenTabMenuPadding__c;
                ZenTabMenuTextAlign = customerBrandingParamentersVal.ZenTabMenuTextAlign__c;
                ZenZenTabMenuPadding = customerBrandingParamentersVal.ZenZenTabMenuPadding__c;
                ZenActiveAHoverBorderWidth = customerBrandingParamentersVal.ZenActiveAHoverBorderWidth__c;
                ZenActiveAHoverBorderColor = customerBrandingParamentersVal.ZenActiveAHoverBorderColor__c;
                ZenActiveAHoverBorderStyle = customerBrandingParamentersVal.ZenActiveAHoverBorderStyle__c;
                ZenActiveAHoverColor = customerBrandingParamentersVal.ZenActiveAHoverColor__c;
                BodyTableMarginBottom = customerBrandingParamentersVal.BodyTableMarginBottom__c; 
                brandSecondaryBrdWidth = customerBrandingParamentersVal.BrandSecondaryBrd_Width__c;
                brandSecondaryBrdMarginLeft = customerBrandingParamentersVal.BrandSecondaryBrd_MarginLeft__c;
                sideBarMarginTop = customerBrandingParamentersVal.SideBar_MarginTop__c;
            }
        }
        system.debug(' CustomerCommunityController :: initializeBrandingParameters :: End ');
    }
}